openapi: 3.0.0
paths:
  /test:
    post:
      description: テスト作成APIの説明
      operationId: test-create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRequestTestDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTestResponseDto'
      summary: テスト作成
      tags: &ref_0
        - Test
  /test/{id}:
    get:
      description: テスト取得APIの説明
      operationId: test-get
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTestResponseDto'
      security:
        - bearer: []
      summary: テスト取得
      tags: *ref_0
  /test/download-csv:
    post:
      description: テストCSVダウンロードAPIの説明
      operationId: test-download-csv
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DownloadCsvRequestDto'
      responses:
        '200':
          description: ''
      summary: テストCSVダウンロード
      tags: *ref_0
  /test/send-async-message:
    post:
      description: 非同期メッセージ送信APIの説明
      operationId: test-send-async-message
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendAsyncMessageRequestDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendAsyncMessageResponseDto'
      summary: 非同期メッセージ送信
      tags: *ref_0
info:
  title: アプリケーション名
  description: APIの説明文
  version: '1.0'
  contact: {}
tags:
  - name: APIタグ
    description: ''
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    CreateRequestTestDto:
      type: object
      properties:
        name:
          type: string
          description: テスト名
          example: test
        email:
          type: string
          description: メールアドレス
          example: test@example.com
        description:
          type: string
          description: テスト説明
          example: test
      required:
        - name
        - email
    CreateTestResponseDto:
      type: object
      properties:
        id:
          type: number
          description: ID
          example: 1
        name:
          type: string
          description: メッセージ
          example: test
        email:
          type: string
          description: メールアドレス
          example: test@example.com
        description:
          type: string
          description: テスト説明
          example: test
      required:
        - id
        - name
        - email
    GetTestResponseDto:
      type: object
      properties:
        id:
          type: number
          description: ID
          example: 1
        name:
          type: string
          description: メッセージ
          example: test
        email:
          type: string
          description: メールアドレス
          example: test@example.com
        description:
          type: string
          description: テスト説明
          example: test
      required:
        - id
        - name
        - email
    DownloadCsvRequestDto:
      type: object
      properties:
        formatType:
          type: string
          description: CSVフォーマットタイプ
          example: A_TYPE
      required:
        - formatType
    SendAsyncMessageRequestDto:
      type: object
      properties:
        message:
          type: string
          description: メッセージ
          example: test
      required:
        - message
    SendAsyncMessageResponseDto:
      type: object
      properties:
        status:
          type: string
          description: ID
          example: success
      required:
        - status
